# Generated by Django 4.1.7 on 2023-03-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(null=True, upload_to='testimonial/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimonial',
            field=models.TextField(null=True),
        ),
    ]
