# Generated by Django 4.1.7 on 2023-03-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_testimonial_image_testimonial_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
